# Generated by Django 3.2.9 on 2022-10-27 22:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='店舗名')),
                ('slug', models.SlugField(unique=True)),
                ('email', models.EmailField(max_length=254, verbose_name='メールアドレス')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Recruit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recruitment_type', models.CharField(blank=True, max_length=50, verbose_name='職種')),
                ('hourlywage', models.CharField(max_length=50, verbose_name='給与')),
                ('hourlywage_description', models.CharField(blank=True, max_length=50, verbose_name='時給詳細')),
                ('worktime', models.CharField(blank=True, max_length=50, verbose_name='勤務時間')),
                ('worktime_description', models.CharField(blank=True, max_length=100, verbose_name='勤務時間詳細')),
                ('description', models.TextField(blank=True, verbose_name='詳細')),
                ('is_publish', models.BooleanField(default=True, verbose_name='公開する')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruit.store')),
            ],
        ),
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='名前')),
                ('age', models.IntegerField(verbose_name='年齢')),
                ('gender', models.CharField(choices=[('1', '女性'), ('2', '男性')], default=1, max_length=2, verbose_name='性別')),
                ('email', models.EmailField(max_length=254, verbose_name='メールアドレス')),
                ('tel', models.CharField(max_length=20, verbose_name='電話番号')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruit.store')),
            ],
        ),
    ]
